services:
  postgres:
    image: "postgres:14"
    container_name: "typeorm-postgres"
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
